PRODUCT_PACKAGES += \
    charger.fstab.qcom \
    fstab.qcom \
    init.class_main.sh \
    init.gbmods.sh \
    init.griffin.rc \
    init.mmi.audio.sh \
    init.mmi.block_perm.sh \
    init.mmi.boot.sh \
    init.mmi.laser.sh \
    init.mmi.usb.rc \
    init.oem.hw.sh \
    init.qcom.class_core.sh \
    init.qcom.early_boot.sh \
    init.qcom.post_boot.sh \
    init.qcom.rc \
    init.qcom.sensors.sh \
    init.qcom.sh \
    init.qcom.syspart_fixup.sh \
    init.target.rc \
    ueventd.qcom.rc \
    wlan_carrier_bin.sh \
    init.mmi.volte.rc \
