PRODUCT_PACKAGES += \
    charger.fstab.qcom \
    fstab.qcom \
    init.class_main.sh \
    init.gbmods.sh \
    init.mdm.sh \
    init.mmi.audio.sh \
    init.mmi.block_perm.sh \
    init.mmi.boot.sh \
    init.mmi.chipset.rc \
    init.mmi.common.rc \
    init.mmi.diag_mdlog.rc \
    init.mmi.laser.sh \
    init.mmi.rc \
    init.mmi.sensor.rc \
    init.mmi.usb.rc \
    init.mmi.usb.sh \
    init.oem.hw.sh \
    init.oem.rc \
    init.qcom.class_core.sh \
    init.qcom.early_boot.sh \
    init.qcom.rc \
    init.qcom.sensors.sh \
    init.qcom.sh \
    init.qcom.syspart_fixup.sh \
    init.target.rc \
    ueventd.qcom.rc \
